### ISSUE TITLE
Stackdriver deployment fails at configure.yml on debian on GCP

### ISSUE THREAD

**Issue by xrl** [GoogleCloudPlatform/stackdriver-ansible-role#14]
I have cloned this repo to my roles folder:

```
git clone https://github.com/GoogleCloudPlatform/stackdriver-ansible-role.git roles/stackdriver
```

and I have started a new playbook `gce_cloud_monitor.yml`:

```

---
- hosts: logging
  vars:
    stackdriver_api_key: "BLEEPBLOORP"
  roles:
  - ../roles/stackdriver
```

and then when I run the playbook I get a failure at the stackdriver configure.yml:

```
TASK [../roles/stackdriver : Determine the Stackdriver host ID for reporting.] *
fatal: [myhost.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "", "parsed": false}
```
